- In this lecture we will see how to make use of specific runtime configuration for creating kubernetes pods
- In the previous lecture we saw that gvisor makes use of the runsC runtime to create containers, assuming that we already have gvisor installed on all kubernetes nodes lets now see how to instruct the pods to specifically make use of this runtime - For this we have to create a new kubernetes object called runtimeclass 
this object has 2 significant Fields we runtime class name which we have called gvisor and secondly the handler which is the runtime to be used by the runtime class 
- for gvisor we will set this to runsC, next use the cube CTL create command to create the runtime class object

gvisor.yaml

apiVersion: node.k8s.io/v1  
kind: RuntimeClass
metadata:
  name: gvisor  
handler: runsc
kubectl create -f gvisor.yml


- here we have a Pod definition file to create an Nginx container to specifically instruct the pod to be created using the gvisor. we can make use of the field runtime class name under the pod spec 
creating the pod now will create the containers using the g-visor runtime class. our port is now running the gyvisor 

gvisor-nginx.yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  runtimeClassName: gvisor
  containers:
  - image: nginx
    name: nginx
kubectl create -f gvisor-nginx.yaml

To test that the container is isolated from the Linux Kernel we can check if the nginx process can be seen on the Node which is running the pod when we run the command (pgrep -a nginx)on the Node the nginx process seems to be missing
this shows the gvisor is doing a good job at sandboxing nginx container hiding what's going on inside from the rest of the system 
we can also see that the runsc Runtime is running on the Node by running cammand (pgrep -a runsc)